chore(sportapp): refactorizacion codigo existente
MateoBohorquezUniandes/MISW4501-2024-11-14-Proyecto-Final-Angular pull request #11
Opened 2024-04-16 04:13 UTC by s-cortes

## Historias de Usuario/Arquitectura Relacionadas

> Coloque la URL y título de las historias relacionadas al Pull Request. Ejemplo:
* [HU000](#): Crear Boilerplate del repositorio

## Changelog

> Describa de forma precisa los cambios realizados en el Pull Request. Ejemplo:
* Se crea el archivo `.github/pull_request_template.md`

## Checklist

> Antes de solicitar reviews, los siguientes elementos deben estar listos

### Generales

- [ ] La rama de origen sigue la convención mencionada en `.github/CONTRIBUTING`
- [ ] Pull Request cuenta con un título apropiado
- [ ] Se ha seleccionado el Milestone correspondiente
- [ ] Se han colocado los labels para (microservicio, estado, tipo)

### CI/CD

- [ ] Se modificaron o agregaron pruebas al backlog
- [ ] Los cambios cuentan con la cobertura mínima de pruebas (70%)
- [ ] Se actualizaron las colecciones de Postman
- [ ] Todos los checks del repositorio han sido exitosos

2024-04-16 18:07 UTC, MateoBohorquezUniandes requested changes

2024-04-16 18:07 UTC, MateoBohorquezUniandes commented on angular.json
> +          "style": "scss"
No cambiar el uso de Css por Scss, hasta el momento se ha usado CSS para el desarrollo, el cambio puede afectar partes visuales ya desarrolladas

2024-04-16 18:07 UTC, MateoBohorquezUniandes commented on angular.json
> +            "inlineStyleLanguage": "scss",
Retirar

2024-04-16 18:07 UTC, MateoBohorquezUniandes commented on angular.json
> +              "src/styles.scss"
Se elimina el paquete de estilos de la libreria Toastr, afectando las notificaciones

2024-04-16 18:07 UTC, MateoBohorquezUniandes commented on docker-compose.yml
No se requiere compose, el ambiente de producción corre de forma independiente con Cloud Run

2024-04-16 18:07 UTC, MateoBohorquezUniandes commented on src/app/app.component.ts
Denegado por Scss

2024-04-17 01:32 UTC, s-cortes commented on angular.json
> +            "inlineStyleLanguage": "scss",
no 😝

2024-05-10 01:28 UTC, closed without merging